import { CFG } from "../core/config.js";

/* The dark seal every cabinet glyph and every foe contour strokes itself
   with — one constant so the two families keep the same craft. */
export const RIM = "rgba(0,0,0,0.55)";

export function rr(c, x, y, w, h, r) {
  c.beginPath();
  c.moveTo(x + r, y);
  c.arcTo(x + w, y, x + w, y + h, r);
  c.arcTo(x + w, y + h, x, y + h, r);
  c.arcTo(x, y + h, x, y, r);
  c.arcTo(x, y, x + w, y, r);
  c.closePath();
}

/* ---- items / power-up icons (cabinet glyphs, readable at 40px) ---- */
export function drawIcon(c, type, col, time) {
  c.save();
  c.lineWidth = 2;
  c.strokeStyle = RIM;
  c.lineJoin = "round";
  c.lineCap = "round";
  c.fillStyle = col;
  const s = CFG.TILE * 0.3;
  const st = () => c.stroke();
  switch (type) {
    case "fire":
      c.beginPath();
      c.moveTo(0, -s * 1.05);
      c.quadraticCurveTo(s * 0.88, -s * 0.12, s * 0.55, s * 0.78);
      c.quadraticCurveTo(s * 0.12, s * 0.32, 0, s * 0.88);
      c.quadraticCurveTo(-s * 0.12, s * 0.32, -s * 0.55, s * 0.78);
      c.quadraticCurveTo(-s * 0.88, -s * 0.12, 0, -s * 1.05);
      c.fill();
      st();
      c.fillStyle = "#ffd447";
      c.beginPath();
      c.moveTo(0, -s * 0.28);
      c.quadraticCurveTo(s * 0.32, s * 0.28, 0, s * 0.58);
      c.quadraticCurveTo(-s * 0.32, s * 0.28, 0, -s * 0.28);
      c.fill();
      c.fillStyle = "#fff3b0";
      c.beginPath();
      c.arc(s * 0.4, -s * 0.52, s * 0.1, 0, 7);
      c.fill();
      break;
    case "bomb":
      c.beginPath();
      c.arc(0, s * 0.14, s * 0.7, 0, 7);
      c.fill();
      st();
      c.strokeStyle = col;
      c.beginPath();
      c.moveTo(s * 0.18, -s * 0.46);
      c.quadraticCurveTo(s * 0.42, -s * 0.72, s * 0.52, -s * 0.95);
      c.stroke();
      c.fillStyle = "#ffd447";
      c.beginPath();
      c.arc(s * 0.55, -s * 0.98, s * 0.14, 0, 7);
      c.fill();
      c.strokeStyle = "#fff";
      c.lineWidth = 2.2;
      c.beginPath();
      c.moveTo(-s * 0.22, s * 0.14);
      c.lineTo(s * 0.22, s * 0.14);
      c.moveTo(0, -s * 0.08);
      c.lineTo(0, s * 0.36);
      c.stroke();
      break;
    case "speed":
      c.beginPath();
      c.moveTo(s * 0.18, -s);
      c.lineTo(-s * 0.55, s * 0.04);
      c.lineTo(-s * 0.04, s * 0.04);
      c.lineTo(-s * 0.22, s);
      c.lineTo(s * 0.62, -s * 0.06);
      c.lineTo(s * 0.1, -s * 0.06);
      c.closePath();
      c.fill();
      st();
      c.strokeStyle = "#cfe6ff";
      c.lineWidth = 1.5;
      c.beginPath();
      c.moveTo(s * 0.04, -s * 0.68);
      c.lineTo(-s * 0.26, -s * 0.02);
      c.stroke();
      break;
    case "heart":
      c.beginPath();
      c.moveTo(0, s * 0.72);
      c.bezierCurveTo(-s * 1.05, -s * 0.04, -s * 0.42, -s * 1.02, 0, -s * 0.26);
      c.bezierCurveTo(s * 0.42, -s * 1.02, s * 1.05, -s * 0.04, 0, s * 0.72);
      c.fill();
      st();
      c.fillStyle = "rgba(255,255,255,0.55)";
      c.beginPath();
      c.arc(-s * 0.22, -s * 0.16, s * 0.14, 0, 7);
      c.fill();
      break;
    case "shield":
      c.beginPath();
      c.moveTo(0, -s);
      c.lineTo(s * 0.82, -s * 0.55);
      c.lineTo(s * 0.72, s * 0.28);
      c.quadraticCurveTo(s * 0.48, s * 0.72, 0, s);
      c.quadraticCurveTo(-s * 0.48, s * 0.72, -s * 0.72, s * 0.28);
      c.lineTo(-s * 0.82, -s * 0.55);
      c.closePath();
      c.fill();
      st();
      c.strokeStyle = "#0d3f78";
      c.lineWidth = 2.2;
      c.beginPath();
      c.moveTo(0, -s * 0.42);
      c.lineTo(s * 0.3, -s * 0.04);
      c.lineTo(0, s * 0.4);
      c.lineTo(-s * 0.3, -s * 0.04);
      c.closePath();
      c.stroke();
      break;
    case "kick":
      c.beginPath();
      c.moveTo(-s * 0.12, -s * 0.78);
      c.lineTo(s * 0.3, -s * 0.78);
      c.lineTo(s * 0.34, s * 0.12);
      c.lineTo(s * 0.88, s * 0.26);
      c.lineTo(s * 0.88, s * 0.64);
      c.lineTo(-s * 0.2, s * 0.64);
      c.closePath();
      c.fill();
      st();
      c.fillStyle = "#8a5326";
      c.fillRect(-s * 0.2, s * 0.48, s * 1.08, s * 0.16);
      c.strokeStyle = "#ffce8a";
      c.lineWidth = 2;
      c.beginPath();
      c.moveTo(-s * 0.88, -s * 0.12);
      c.lineTo(-s * 0.42, 0);
      c.lineTo(-s * 0.88, s * 0.12);
      c.stroke();
      break;
    case "throw":
      c.strokeStyle = col;
      c.lineWidth = s * 0.2;
      c.beginPath();
      c.arc(-s * 0.08, s * 0.42, s * 0.88, Math.PI * 1.12, Math.PI * 1.85);
      c.stroke();
      c.fillStyle = col;
      c.beginPath();
      c.arc(s * 0.7, -s * 0.38, s * 0.3, 0, 7);
      c.fill();
      c.strokeStyle = "rgba(0,0,0,0.55)";
      c.lineWidth = 2;
      c.stroke();
      c.fillStyle = "#ffd447";
      c.beginPath();
      c.arc(s * 0.8, -s * 0.55, s * 0.1, 0, 7);
      c.fill();
      break;
    case "pass":
      c.strokeStyle = col;
      c.lineWidth = 2.2;
      c.beginPath();
      c.moveTo(-s * 0.55, -s * 0.55);
      c.lineTo(s * 0.55, -s * 0.55);
      c.stroke();
      c.beginPath();
      c.moveTo(-s * 0.55, s * 0.55);
      c.lineTo(s * 0.55, s * 0.55);
      c.stroke();
      c.beginPath();
      c.moveTo(-s * 0.7, -s * 0.32);
      c.lineTo(-s * 0.7, s * 0.32);
      c.stroke();
      c.beginPath();
      c.moveTo(s * 0.7, -s * 0.32);
      c.lineTo(s * 0.7, s * 0.32);
      c.stroke();
      c.lineWidth = s * 0.2;
      c.beginPath();
      c.moveTo(-s * 0.78, 0);
      c.lineTo(s * 0.32, 0);
      c.stroke();
      c.fillStyle = col;
      c.beginPath();
      c.moveTo(s * 0.22, -s * 0.3);
      c.lineTo(s * 0.85, 0);
      c.lineTo(s * 0.22, s * 0.3);
      c.closePath();
      c.fill();
      break;
    case "line":
      c.strokeStyle = col;
      c.lineWidth = s * 0.26;
      c.beginPath();
      c.moveTo(-s, 0);
      c.lineTo(s * 0.32, 0);
      c.stroke();
      c.fillStyle = col;
      c.beginPath();
      c.moveTo(s * 0.18, -s * 0.4);
      c.lineTo(s * 1.05, 0);
      c.lineTo(s * 0.18, s * 0.4);
      c.closePath();
      c.fill();
      c.lineWidth = 2;
      c.beginPath();
      c.moveTo(-s * 0.55, -s * 0.38);
      c.lineTo(-s * 0.28, -s * 0.38);
      c.moveTo(-s * 0.08, -s * 0.38);
      c.lineTo(s * 0.18, -s * 0.38);
      c.stroke();
      break;
    case "power":
      c.beginPath();
      c.moveTo(0, -s * 1.05);
      c.lineTo(s * 0.22, -s * 0.22);
      c.lineTo(s * 1.05, 0);
      c.lineTo(s * 0.22, s * 0.22);
      c.lineTo(0, s * 1.05);
      c.lineTo(-s * 0.22, s * 0.22);
      c.lineTo(-s * 1.05, 0);
      c.lineTo(-s * 0.22, -s * 0.22);
      c.closePath();
      c.fill();
      st();
      c.fillStyle = "#fff";
      c.beginPath();
      c.arc(0, 0, s * 0.16, 0, 7);
      c.fill();
      break;
    case "pierce":
      c.fillStyle = "#12203a";
      c.fillRect(-s * 0.88, -s * 0.72, s * 0.28, s * 0.48);
      c.fillRect(-s * 0.88, s * 0.24, s * 0.28, s * 0.48);
      c.fillStyle = col;
      c.beginPath();
      c.moveTo(-s * 0.98, -s * 0.14);
      c.lineTo(s * 0.22, -s * 0.14);
      c.lineTo(s * 0.22, -s * 0.4);
      c.lineTo(s * 0.98, 0);
      c.lineTo(s * 0.22, s * 0.4);
      c.lineTo(s * 0.22, s * 0.14);
      c.lineTo(-s * 0.98, s * 0.14);
      c.closePath();
      c.fill();
      st();
      break;
    case "remote":
      c.fillStyle = col;
      rr(c, -s * 0.55, s * 0.08, s * 1.1, s * 0.68, 3);
      c.fill();
      st();
      c.fillStyle = "#3a4256";
      rr(c, -s * 0.34, s * 0.22, s * 0.68, s * 0.38, 2);
      c.fill();
      c.fillStyle = col;
      c.fillRect(-s * 0.1, -s * 0.52, s * 0.2, s * 0.64);
      c.fillRect(-s * 0.42, -s * 0.75, s * 0.84, s * 0.22);
      c.fillStyle = "#ff5d73";
      c.beginPath();
      c.arc(s * 0.28, s * 0.4, s * 0.1, 0, 7);
      c.fill();
      break;
  }
  c.restore();
}
